// Generated by Supabase Type Generator
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          email: string
          name: string | null
          avatar: string | null
          role: 'USER' | 'CREATOR' | 'ADMIN'
          email_verified: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          email: string
          name?: string | null
          avatar?: string | null
          role?: 'USER' | 'CREATOR' | 'ADMIN'
          email_verified?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          name?: string | null
          avatar?: string | null
          role?: 'USER' | 'CREATOR' | 'ADMIN'
          email_verified?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      solutions: {
        Row: {
          id: string
          title: string
          description: string
          category_id: string
          created_by: string
          status: 'DRAFT' | 'PENDING' | 'APPROVED' | 'REJECTED'
          featured: boolean
          view_count: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          title: string
          description: string
          category_id: string
          created_by: string
          status?: 'DRAFT' | 'PENDING' | 'APPROVED' | 'REJECTED'
          featured?: boolean
          view_count?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          title?: string
          description?: string
          category_id?: string
          created_by?: string
          status?: 'DRAFT' | 'PENDING' | 'APPROVED' | 'REJECTED'
          featured?: boolean
          view_count?: number
          created_at?: string
          updated_at?: string
        }
      }
      categories: {
        Row: {
          id: string
          name: string
          description: string | null
          icon: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          description?: string | null
          icon?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          description?: string | null
          icon?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      tags: {
        Row: {
          id: string
          name: string
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          created_at?: string
        }
      }
      solution_tags: {
        Row: {
          solution_id: string
          tag_id: string
        }
        Insert: {
          solution_id: string
          tag_id: string
        }
        Update: {
          solution_id?: string
          tag_id?: string
        }
      }
      reviews: {
        Row: {
          id: string
          solution_id: string
          user_id: string
          rating: number
          comment: string | null
          status: 'PENDING' | 'APPROVED' | 'REJECTED'
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          solution_id: string
          user_id: string
          rating: number
          comment?: string | null
          status?: 'PENDING' | 'APPROVED' | 'REJECTED'
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          solution_id?: string
          user_id?: string
          rating?: number
          comment?: string | null
          status?: 'PENDING' | 'APPROVED' | 'REJECTED'
          created_at?: string
          updated_at?: string
        }
      }
      bookmarks: {
        Row: {
          id: string
          user_id: string
          solution_id: string
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          solution_id: string
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          solution_id?: string
          created_at?: string
        }
      }
      files: {
        Row: {
          id: string
          filename: string
          original_name: string
          mime_type: string
          size: number
          path: string
          public: boolean
          uploaded_by: string
          created_at: string
        }
        Insert: {
          id?: string
          filename: string
          original_name: string
          mime_type: string
          size: number
          path: string
          public?: boolean
          uploaded_by: string
          created_at?: string
        }
        Update: {
          id?: string
          filename?: string
          original_name?: string
          mime_type?: string
          size?: number
          path?: string
          public?: boolean
          uploaded_by?: string
          created_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
