# 本地开发环境覆盖配置
# 这个文件会自动与 docker-compose.yml 合并

version: '3.8'

services:
  app:
    build:
      target: dev
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    command: npm run dev

  db:
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=development_password

  redis:
    ports:
      - "6379:6379"

  nginx:
    # 在开发环境中禁用 nginx
    profiles:
      - production