# 本地开发环境覆盖配置
# 这个文件会自动与 docker-compose.yml 合并

version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
      - app_next:/app/.next
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://openaero:openaero123@db:5432/openaero
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your-super-secret-jwt-key-here-change-in-production
      - NEXT_PUBLIC_APP_URL=http://openaero.cn:3000
    depends_on:
      - db
      - redis

  db:
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password

  redis:
    ports:
      - "6379:6379"

  nginx:
    # 在开发环境中禁用 nginx
    profiles:
      - production

volumes:
  app_next: