project:
  name: "openaero.web"
  description: "开元空御 - 社区驱动的开放式无人机解决方案平台"
  version: "1.0.0"
  type: "web-application"

ai_assistant:
  name: "cursor-agent"
  type: "cursor"

directories:
  specs: "specs"
  plans: "specs"
  tasks: "specs"
  docs: "docs"

templates:
  feature: "feature-template.md"
  plan: "plan-template.md"
  task: "task-template.md"

workflow:
  auto_generate_tasks: true
  auto_update_plan: true
  validation_strict: true

git:
  auto_commit: false
  branch_prefix: "spec/"
