-- OpenAero Database Rebuild Script
-- WARNING: This will DROP ALL existing tables and data!

BEGIN;

-- Drop all existing tables in reverse dependency order
DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS product_reviews CASCADE;
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS cart_items CASCADE;
DROP TABLE IF EXISTS carts CASCADE;
DROP TABLE IF EXISTS product_inventory CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS product_categories CASCADE;
DROP TABLE IF EXISTS sample_orders CASCADE;
DROP TABLE IF EXISTS factories CASCADE;
DROP TABLE IF EXISTS favorites CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;
DROP TABLE IF EXISTS revenue_shares CASCADE;
DROP TABLE IF EXISTS payment_events CASCADE;
DROP TABLE IF EXISTS payment_transactions CASCADE;
DROP TABLE IF EXISTS order_solutions CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS solution_reviews CASCADE;
DROP TABLE IF EXISTS solution_files CASCADE;
DROP TABLE IF EXISTS solution_versions CASCADE;
DROP TABLE IF EXISTS solutions CASCADE;
DROP TABLE IF EXISTS creator_profiles CASCADE;
DROP TABLE IF EXISTS user_profiles CASCADE;

-- Drop all enums
DROP TYPE IF EXISTS "NotificationPriority" CASCADE;
DROP TYPE IF EXISTS "NotificationType" CASCADE;
DROP TYPE IF EXISTS "CartStatus" CASCADE;
DROP TYPE IF EXISTS "InventoryStatus" CASCADE;
DROP TYPE IF EXISTS "ProductStatus" CASCADE;
DROP TYPE IF EXISTS "ReviewDecision" CASCADE;
DROP TYPE IF EXISTS "ReviewStatus" CASCADE;
DROP TYPE IF EXISTS "FileStatus" CASCADE;
DROP TYPE IF EXISTS "SolutionFileType" CASCADE;
DROP TYPE IF EXISTS "SampleOrderStatus" CASCADE;
DROP TYPE IF EXISTS "FactoryStatus" CASCADE;
DROP TYPE IF EXISTS "RevenueStatus" CASCADE;
DROP TYPE IF EXISTS "PaymentEventType" CASCADE;
DROP TYPE IF EXISTS "PaymentStatus" CASCADE;
DROP TYPE IF EXISTS "PaymentMethod" CASCADE;
DROP TYPE IF EXISTS "OrderStatus" CASCADE;
DROP TYPE IF EXISTS "SolutionStatus" CASCADE;
DROP TYPE IF EXISTS "CreatorStatus" CASCADE;
DROP TYPE IF EXISTS "UserStatus" CASCADE;
DROP TYPE IF EXISTS "UserRole" CASCADE;

COMMIT;

-- Now use Prisma to create the new schema
-- Run: npx prisma db push
