openapi: 3.0.0
info:
  title: OpenAero Authentication API
  description: 用户认证系统API接口规范
  version: 1.0.0
  contact:
    name: OpenAero Team
    email: dev@openaero.com

servers:
  - url: https://api.openaero.com
    description: Production server
  - url: http://localhost:3000
    description: Development server

paths:
  /api/auth/register:
    post:
      summary: 用户注册
      description: 新用户注册账户
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - firstName
              properties:
                email:
                  type: string
                  format: email
                  example: user@example.com
                password:
                  type: string
                  minLength: 8
                  example: "securePassword123"
                firstName:
                  type: string
                  example: "张"
                lastName:
                  type: string
                  example: "三"
      responses:
        '201':
          description: 注册成功，发送验证邮件
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "注册成功，请检查邮箱完成验证"
                  userId:
                    type: string
                    example: "user_123"
        '400':
          description: 请求参数错误
        '409':
          description: 邮箱已存在
        '500':
          description: 服务器内部错误

  /api/auth/verify-email:
    post:
      summary: 验证邮箱
      description: 通过令牌验证用户邮箱
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - token
              properties:
                token:
                  type: string
                  example: "verification_token_abc123"
      responses:
        '200':
          description: 邮箱验证成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "邮箱验证成功"
                  user:
                    $ref: '#/components/schemas/User'
        '400':
          description: 令牌无效或已过期
        '404':
          description: 令牌不存在

  /api/auth/login:
    post:
      summary: 用户登录
      description: 用户使用邮箱和密码登录
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  example: user@example.com
                password:
                  type: string
                  example: "securePassword123"
                rememberMe:
                  type: boolean
                  example: true
      responses:
        '200':
          description: 登录成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/User'
                  session:
                    $ref: '#/components/schemas/Session'
        '401':
          description: 邮箱或密码错误
        '403':
          description: 邮箱未验证
        '429':
          description: 登录尝试次数过多

  /api/auth/logout:
    post:
      summary: 用户登出
      description: 终止当前用户会话
      tags:
        - Authentication
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 登出成功
        '401':
          description: 未授权访问

  /api/auth/forgot-password:
    post:
      summary: 忘记密码
      description: 请求密码重置邮件
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
              properties:
                email:
                  type: string
                  format: email
                  example: user@example.com
      responses:
        '200':
          description: 重置邮件已发送
        '404':
          description: 邮箱不存在
        '429':
          description: 请求次数过多

  /api/auth/reset-password:
    post:
      summary: 重置密码
      description: 使用令牌重置密码
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - token
                - newPassword
              properties:
                token:
                  type: string
                  example: "reset_token_xyz789"
                newPassword:
                  type: string
                  minLength: 8
                  example: "newSecurePassword456"
      responses:
        '200':
          description: 密码重置成功
        '400':
          description: 令牌无效或已过期

  /api/auth/session:
    get:
      summary: 获取会话信息
      description: 获取当前用户会话信息
      tags:
        - Authentication
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 会话信息
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/User'
                  session:
                    $ref: '#/components/schemas/Session'
        '401':
          description: 未授权或会话过期

  /api/auth/sessions:
    get:
      summary: 获取活跃会话列表
      description: 获取用户所有活跃会话
      tags:
        - Authentication
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 会话列表
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Session'
        '401':
          description: 未授权访问

  /api/auth/sessions/{sessionId}:
    delete:
      summary: 终止指定会话
      description: 终止用户指定的会话
      tags:
        - Authentication
      security:
        - bearerAuth: []
      parameters:
        - name: sessionId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 会话终止成功
        '401':
          description: 未授权访问
        '404':
          description: 会话不存在

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          example: "user_123"
        email:
          type: string
          format: email
          example: user@example.com
        firstName:
          type: string
          example: "张"
        lastName:
          type: string
          example: "三"
        avatar:
          type: string
          example: "https://example.com/avatar.jpg"
        role:
          type: string
          enum: ["USER", "CREATOR", "ADMIN", "SUPER_ADMIN"]
        emailVerified:
          type: boolean
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    Session:
      type: object
      properties:
        id:
          type: string
          example: "session_abc123"
        deviceInfo:
          type: object
          properties:
            browser:
              type: string
              example: "Chrome"
            os:
              type: string
              example: "Windows"
            deviceType:
              type: string
              example: "desktop"
        ipAddress:
          type: string
          example: "192.168.1.1"
        lastUsedAt:
          type: string
          format: date-time
        createdAt:
          type: string
          format: date-time
        expiresAt:
          type: string
          format: date-time

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []